/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLOUDFS_LOCK_SERVICE_H_RPCGEN
#define _CLOUDFS_LOCK_SERVICE_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif

#define MAXNAMELEN 255

typedef char *keyname;

enum status {
	ERROR = 0,
	OK = 1,
	UNALLOC = 2,
};
typedef enum status status;

enum type {
	UNDEFINED = 0,
	READ = 1,
	WRITE = 2,
	RELEASE = 3,
};
typedef enum type type;

struct identity {
	int id_arr[2];
};
typedef struct identity identity;

struct lock_params {
	keyname key;
	type operation;
	identity id;
};
typedef struct lock_params lock_params;

typedef struct lock_item {
        int i;
        pthread_mutex_t mutex;
        pthread_cond_t cond;
        type operation;
} lock_item;

#define LOCKSERVICEPROG 0x20000002
#define LOCKSERVICEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ACQUIRE 1
extern  enum clnt_stat acquire_1(lock_params *, status *, CLIENT *);
extern  bool_t acquire_1_svc(lock_params *, status *, struct svc_req *);
#define RELEASE 2
extern  enum clnt_stat release_1(lock_params *, status *, CLIENT *);
extern  bool_t release_1_svc(lock_params *, status *, struct svc_req *);
extern int lockserviceprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ACQUIRE 1
extern  enum clnt_stat acquire_1();
extern  bool_t acquire_1_svc();
#define RELEASE 2
extern  enum clnt_stat release_1();
extern  bool_t release_1_svc();
extern int lockserviceprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_keyname (XDR *, keyname*);
extern  bool_t xdr_status (XDR *, status*);
extern  bool_t xdr_type (XDR *, type*);
extern  bool_t xdr_identity (XDR *, identity*);
extern  bool_t xdr_lock_params (XDR *, lock_params*);

#else /* K&R C */
extern bool_t xdr_keyname ();
extern bool_t xdr_status ();
extern bool_t xdr_type ();
extern bool_t xdr_identity ();
extern bool_t xdr_lock_params ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CLOUDFS_LOCK_SERVICE_H_RPCGEN */
